### ISSUE TITLE
$rdf is not defined

### ISSUE THREAD

**Issue by jaxoncreed** [jeff-zucker/solid-file-client#225]
Hey Jeff,

First time using solid-file-client. I had some trouble with the following error: `ReferenceError: $rdf is not defined`. It seems that something wants rdflib, but it can't get it. Here's my code:

```typescript
import { SolidNodeClient } from "solid-node-client";
import SolidFileClient from "solid-file-client";

const auth = new SolidNodeClient();
const fileClient = new SolidFileClient(auth);

async function run() {
  const inputPath = "/clone-to-solid-pod/testClone/";
  const targetContainer = "https://solidweb.me/jackson/cloned/";
  const refreshToken = ".....";
  const clientId = ".....";
  const clientSecret = "....";
  const oidcIssuer = "https://solidweb.me/";

  let session = await auth.login({
    clientId,
    clientSecret,
    refreshToken,
    oidcIssuer,
  });

  if(session.isLoggedIn){
    await fileClient.copyFolder(`file://${inputPath}`, targetContainer);
  }
}
run();
```

solid-file-client@2.1.0 and solid-node-client@2.1.0

**Comment by jeff-zucker** [comment]
Hmm, are you sure you aren't doing anything else other than what you show there?  I copied it locally and changed only the target and jwt and got no errors and the stuff cloned correctly.  AFAIK the only reason solid-node-client would need $rdflib is the stuff mentioned in the README about patch of local files.

**Comment by jaxoncreed** [comment]
Sorry, I didn't include the call stack.

```
ReferenceError: $rdf is not defined
    at /Users/jackson/O/clone-to-solid-pod/node_modules/@solid-rest/core/dist/cjs/handleResponse.js:128:15
    at new Promise (<anonymous>)
    at serialize (/Users/jackson/O/clone-to-solid-pod/node_modules/@solid-rest/core/dist/cjs/handleResponse.js:127:12)
    at SolidRest.handleResponse (/Users/jackson/O/clone-to-solid-pod/node_modules/@solid-rest/core/dist/cjs/handleResponse.js:142:20)
    at async SolidRest.fetch (/Users/jackson/O/clone-to-solid-pod/node_modules/@solid-rest/core/dist/cjs/index.js:55:12)
```

The problem seems to be here https://github.com/solid/solid-rest/blob/main/core/src/handleResponse.js#L116. Any ideas?

I don't think I'm doing anything else locally. The project uses typescript, but I don't think that should affect anything.

**Comment by jeff-zucker** [comment]
Oh, darn, yes.  I added ability to pass JSON-LD in the accept header and that uses $rdf.  It would only get triggered when passed an explicity accept header which is why it failed for you and not me.  I'll fix trap it and document it.  Thanks!

**Comment by jaxoncreed** [comment]
Cool thanks!

**Comment by jaxoncreed** [comment]
Hey @jeff-zucker do you know when this will be fixed?

**Comment by jeff-zucker** [comment]
I will do it today.

**Comment by jeff-zucker** [comment]
Version 2.1.1 of solid-node-client should now include version 2.1.8 of @solid-rest/file which should now include version 2.14 of @solid-rest/core which should solve this problem in solid-file-client.

**Comment by jaxoncreed** [comment]
Awesome! Thanks

**Comment by jaxoncreed** [comment]
Okay, I'll close out this issue, but I've encountered another problem in this issue: https://github.com/solid/solid-rest/issues/76

**Comment by jaxoncreed** [comment]
Hey, sorry for the delay in testing. I'm still experiencing the problem.

To recreate it, go to this repo: https://github.com/o-development/clone-to-solid-pod and follow the instructions labeled "Running the program without the github hook" in the readme.

You should see the message `ReferenceError: $rdf is not defined`

**Comment by jeff-zucker** [comment]
Fixed in https://github.com/o-development/clone-to-solid-pod/pull/1
